/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shcm.shsupercm.fabric.fletchingtable;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

public class FletchingTablePlugin implements Plugin<Project> {
    public void apply(Project project) {
        
    }
}
