/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shcm.shsupercm.fabric.fletchingtable;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.file.FileCollection;
import org.gradle.api.plugins.JavaPlugin;

public class FTGradlePlugin implements Plugin<Project> {
    @Override
    public void apply(Project project) {
        project.afterEvaluate(this::afterEvaluate);
    }

    private void afterEvaluate(Project project) {
        // Add plugin to project's compileOnly
        FileCollection thisJar = project.files(getClass().getProtectionDomain().getCodeSource().getLocation());
        project.getDependencies().add(JavaPlugin.COMPILE_ONLY_CONFIGURATION_NAME, thisJar);
        project.getDependencies().add(JavaPlugin.ANNOTATION_PROCESSOR_CONFIGURATION_NAME, thisJar);
    }
}
